# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Import Datasets - train and test

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


# Data Preprocessing

In [5]:
#Set 'PassengerId' feature as Index
train.set_index("PassengerId", inplace=True)
test.set_index("PassengerId", inplace=True)

In [6]:
train

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...                                                        ...     ...   ...   
887                                      Montvila, Rev. Juozas    male  27.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                      Behr, Mr. Karl Howell    male  26.0   
891                                        Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
...            ...    ...               ...      ...   ...      ...  
887              0      0            211536  13.0000   NaN        S  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  
890              0      0            111369  30.0000  C148        C  
891              0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [7]:
test

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
...             ...                                           ...     ...   
1305              3                            Spector, Mr. Woolf    male   
1306              1                  Oliva y Ocana, Dona. Fermina  female   
1307              3                  Saether, Mr. Simon Sivertsen    male   
1308              3                           Ware, Mr. Frederick    male   
1309              3                      Peter, Master. Michael J    male   

              Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
PassengerId                                                                   
892          34.5      0      0              330911    7.8292   NaN        Q  
893          47.0      1      0              363272    7.0000   NaN        S  
894          62.0      0      0              240276    9.6875   NaN        Q  
895          27.0      0      0              315154    8.6625   NaN        S  
896          22.0      1      1             3101298   12.2875   NaN        S  
...           ...    ...    ...                 ...       ...   ...      ...  
1305          NaN      0      0           A.5. 3236    8.0500   NaN        S  
1306         39.0      0      0            PC 17758  108.9000  C105        C  
1307         38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
1308          NaN      0      0              359309    8.0500   NaN        S  
1309          NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 10 columns]

# Define features(X) and target label(y) of Training and Testing data

In [8]:
y_train = train['Survived']

In [9]:
y_train

PassengerId
1      0
2      1
3      1
4      1
5      0
      ..
887    0
888    1
889    0
890    1
891    0
Name: Survived, Length: 891, dtype: int64

In [10]:
train.drop(labels="Survived",axis=1,inplace=True)

In [11]:
train.shape

(891, 10)

In [12]:
train_test = pd.concat([train, test])

# Remove Columns

In [13]:
# Removed columns "Name", "Age", "SibSp", "Ticket", "Cabin", "Parch", and "Embarked"

columns_to_drop = ['Name','Age','SibSp','Ticket','Cabin','Parch','Embarked']
train_test.drop(labels=columns_to_drop, axis=1, inplace=True)

In [14]:
train_test

Pclass     Sex      Fare
PassengerId                          
1                 3    male    7.2500
2                 1  female   71.2833
3                 3  female    7.9250
4                 1  female   53.1000
5                 3    male    8.0500
...             ...     ...       ...
1305              3    male    8.0500
1306              1  female  108.9000
1307              3    male    7.2500
1308              3    male    8.0500
1309              3    male   22.3583

[1309 rows x 3 columns]

# Convert objects to numbers with pandas.get_dummies

In [15]:
train_test_dummies = pd.get_dummies(train_test, columns=['Sex'])

In [16]:
train_test_dummies.shape

(1309, 4)

# Chech for Null Value

In [17]:
train_test_dummies.isnull().sum()

Pclass        0
Fare          1
Sex_female    0
Sex_male      0
dtype: int64

In [18]:
# FILL NULL VALUE WITH 0.0

train_test_dummies.fillna(value=0.0, inplace=True)
train_test_dummies.isnull().sum()

Pclass        0
Fare          0
Sex_female    0
Sex_male      0
dtype: int64

In [19]:
X_train = train_test_dummies.values[0:891]
X_test = train_test_dummies.values[891:]

# Transformed data with MinMaxScaler() method

In [20]:
scaler=MinMaxScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

# Randomly splited training set into train and validation subsets

In [21]:
from sklearn.model_selection import train_test_split
X_train_sub, X_validation_sub, y_train_sub, y_validation_sub = train_test_split(X_train_scale, y_train, random_state=0)

# Build the model

In [22]:
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]

In [23]:
def train_and_evaluate(X_train, y_train, X_validation, y_validation, learning_rate):
    gb = GradientBoostingClassifier(n_estimators=20, learning_rate=learning_rate, max_features=2, max_depth=2, random_state=0)
    gb.fit(X_train, y_train)
    
    print("Learning rate:", learning_rate)
    
    # Make predictions on training and validation sets
    y_train_pred = gb.predict(X_train)
    y_validation_pred = gb.predict(X_validation)
    
    # Display confusion matrix and classification report
    print("Confusion Matrix (training):")
    print(confusion_matrix(y_train, y_train_pred))
    
    print("\nClassification Report (training):")
    print(classification_report(y_train, y_train_pred))
    
    print("\nConfusion Matrix (validation):")
    print(confusion_matrix(y_validation, y_validation_pred))
    
    print("\nClassification Report (validation):")
    print(classification_report(y_validation, y_validation_pred))
    
    print()

# learning_rates list
for learning_rate in learning_rates:
    train_and_evaluate(X_train_sub, y_train_sub, X_validation_sub, y_validation_sub, learning_rate)


Learning rate: 0.05
Confusion Matrix (training):
[[353  57]
 [ 84 174]]

Classification Report (training):
              precision    recall  f1-score   support

           0       0.81      0.86      0.83       410
           1       0.75      0.67      0.71       258

    accuracy                           0.79       668
   macro avg       0.78      0.77      0.77       668
weighted avg       0.79      0.79      0.79       668


Confusion Matrix (validation):
[[115  24]
 [ 25  59]]

Classification Report (validation):
              precision    recall  f1-score   support

           0       0.82      0.83      0.82       139
           1       0.71      0.70      0.71        84

    accuracy                           0.78       223
   macro avg       0.77      0.76      0.77       223
weighted avg       0.78      0.78      0.78       223


Learning rate: 0.1
Confusion Matrix (training):
[[353  57]
 [ 82 176]]

Classification Report (training):
              precision    recall  f1-sc

In [24]:
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
  gb = GradientBoostingClassifier(n_estimators=20, learning_rate = learning_rate , max_features=2, max_depth = 2, random_state = 0)
  gb.fit(X_train_sub, y_train_sub)
  print("Learning rate: ",learning_rate)
  print("Accuracy score(training): {0:.3f}".format(gb.score(X_train_sub, y_train_sub)))
  print("Accuracy score(validation): {0:.3f}".format(gb.score(X_validation_sub, y_validation_sub)))
  print()

Learning rate:  0.05
Accuracy score(training): 0.789
Accuracy score(validation): 0.780

Learning rate:  0.1
Accuracy score(training): 0.792
Accuracy score(validation): 0.780

Learning rate:  0.25
Accuracy score(training): 0.816
Accuracy score(validation): 0.803

Learning rate:  0.5
Accuracy score(training): 0.826
Accuracy score(validation): 0.834

Learning rate:  0.75
Accuracy score(training): 0.831
Accuracy score(validation): 0.789

Learning rate:  1
Accuracy score(training): 0.831
Accuracy score(validation): 0.789



# Best Learning Rate for training the final model

In [25]:
best_learning_rate = 0.5
final_model = GradientBoostingClassifier(n_estimators=20, learning_rate=best_learning_rate, max_features=2, max_depth=2, random_state=0)
final_model.fit(X_train_scale, y_train)

GradientBoostingClassifier(learning_rate=0.5, max_depth=2, max_features=2,
                           n_estimators=20, random_state=0)

# Make Predictions

In [26]:
# Make predictions on the test set
predictions = final_model.predict(X_test_scale)

In [27]:
# Create a DataFrame for the submission
submission_df = pd.DataFrame({
    'PassengerId': test.index,
    'Survived': predictions
})

In [28]:
submission_df.shape

(418, 2)

In [29]:
submission_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
dtypes: int64(2)
memory usage: 6.7 KB


In [30]:
submission_df['Survived'].value_counts()

0    281
1    137
Name: Survived, dtype: int64

In [31]:
# Save the predictions to a CSV file
submission_df.to_csv('submission.csv', index=False)